IMAGES = beach.jpg bridge.jpg
THUMB_WIDTH = 320
WEBPAGE = gallery.html
OUTPUT_DIR = dist

IMAGE_FILES = $(patsubst %.jpg,$(OUTPUT_DIR)/%.jpg,$(IMAGES))
THUMB_FILES = $(patsubst %.jpg,$(OUTPUT_DIR)/%.thumb.jpg,$(IMAGES))

$(OUTPUT_DIR)/$(WEBPAGE): $(IMAGE_FILES) $(THUMB_FILES) \
                          gallery.mako gallery.py
	python3 gallery.py $(IMAGES) > $@

.PHONY: clean
clean:
	rm -rf $(OUTPUT_DIR)

$(OUTPUT_DIR)/%.jpg: %.jpg $(OUTPUT_DIR)
	cp $< $@

$(OUTPUT_DIR)/%.thumb.jpg: %.jpg $(OUTPUT_DIR)
	convert -resize $(THUMB_WIDTH)x $< $@

$(OUTPUT_DIR):
	mkdir $(OUTPUT_DIR)
