gallery.html: beach.jpg bridge.jpg \
              beach.thumb.jpg bridge.thumb.jpg \
			  gallery.mako gallery.py
	python3 gallery.py beach.jpg bridge.jpg > gallery.html

beach.thumb.jpg: beach.jpg
	convert -resize 320x beach.jpg beach.thumb.jpg

bridge.thumb.jpg: bridge.jpg
	convert -resize 320x bridge.jpg bridge.thumb.jpg
